version: '3.8'

services:
  # PostgreSQL database
  postgres:
    image: postgres:15-alpine
    container_name: socialproof-postgres
    environment:
      POSTGRES_DB: socialproof
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - socialproof-network

  # Redis for caching and real-time data
  redis:
    image: redis:7-alpine
    container_name: socialproof-redis
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - socialproof-network

  # ClickHouse for analytics
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: socialproof-clickhouse
    environment:
      CLICKHOUSE_DB: socialproof_analytics
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: ''
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./clickhouse/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - socialproof-network

  # Next.js application (development)
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: development
    container_name: socialproof-app
    ports:
      - "3000:3000"
      - "3001:3001"  # WebSocket server
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/socialproof
      - REDIS_URL=redis://redis:6379
      - CLICKHOUSE_URL=http://clickhouse:8123
      - NEXTAUTH_URL=http://localhost:3000
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - postgres
      - redis
      - clickhouse
    networks:
      - socialproof-network

  # Nginx for load balancing (production)
  nginx:
    image: nginx:alpine
    container_name: socialproof-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - app
    networks:
      - socialproof-network
    profiles:
      - production

volumes:
  postgres_data:
  redis_data:
  clickhouse_data:

networks:
  socialproof-network:
    driver: bridge