apiVersion: v1
kind: Namespace
metadata:
  name: lead-scoring
  labels:
    name: lead-scoring
    environment: production
    app.kubernetes.io/name: lead-scoring-tool
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: namespace
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: lead-scoring-quota
  namespace: lead-scoring
spec:
  hard:
    requests.cpu: "10"
    requests.memory: 20Gi
    limits.cpu: "20"
    limits.memory: 40Gi
    persistentvolumeclaims: "10"
    pods: "20"
    services: "10"
    secrets: "10"
    configmaps: "10"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: lead-scoring-limits
  namespace: lead-scoring
spec:
  limits:
  - default:
      cpu: "1000m"
      memory: "2Gi"
    defaultRequest:
      cpu: "100m"
      memory: "256Mi"
    type: Container
  - max:
      cpu: "4000m"
      memory: "8Gi"
    min:
      cpu: "50m"
      memory: "128Mi"
    type: Container